### ISSUE TITLE
TypeError: backoff.on_exception when running in uvicorn

### ISSUE THREAD

**Issue by dj0nes** [launchdarkly/python-server-sdk#135]
**Describe the bug**
I noticed the following error when trying to use launch darkly in a fastapi project with code reloading:

```
TypeError: backoff.on_exception applied to a regular function inside coroutine, this will lead to event loop hiccups. Use backoff.on_exception on coroutines in asynchronous code.
```

The error is thrown from [this line](https://github.com/launchdarkly/python-server-sdk/blob/8adfe4c1607ca5a890b436491d9bec77ed2e1b6f/ldclient/streaming.py#L85) in python-server-sdk.

The command to run uvicorn is [here](https://github.com/tiangolo/uvicorn-gunicorn-docker/blob/8e690ce601f28d204411c48749943653c48ffe59/python3.7-alpine3.8/start-reload.sh#L28) in the base image.

**To reproduce**
I created a [simple repo](https://github.com/dj0nes/ldclient-uvicorn-issue) to reproduce the issue.

```bash
git clone https://github.com/dj0nes/ldclient-uvicorn-issue.git
docker-compose up
```

**Expected behavior**
The application should run without crashing.

**SDK version**
`launchdarkly-server-sdk~=6.11.1`

**Language version, developer tools**
python 3.7

**OS/platform**
alpine 3.8

**Comment by bwoskow-ld** [comment]
Hi @dj0nes,

Thanks for letting us know about this issue. I have to admit, prior to this issue I had never heard of uvicorn. Our team here is unfamiliar with it. As such, we don't currently claim compatibility with uvicorn.

After some investigation I found that the [`backoff` package](https://github.com/litl/backoff) used by our Python SDK has an [open issue](https://github.com/litl/backoff/issues/83) to address the uvicorn incompatibility.  That issue currently has an open question about steps to reproduce the issue -- perhaps you can chime in there. Once that issue is addressed in a new release, we can look into bumping our Python SDK to the newer package version. 

We're on a bit of an old `backoff` version right now (`1.4.3` from two and a half years ago) and I don't know what else lurks in between our version and an upcoming version. As such we can't guarantee that we'll be able to update-- for example, newer `backoff` versions might drop compatibility with Python versions which our SDK still supports. Yet, we can consider it once available. If you're up for it, when a new `backoff` version is available, you can submit a pull request to this repository to apply the fix.

Cheers,
Ben

**Comment by dj0nes** [comment]
Hi Ben, thanks for looking into the issue! I'll see if I can help on the backoff issue you mentioned, and open a PR here if they can get a fix out.

Closing this for now.

**Comment by dj0nes** [comment]
Good news! I no longer see this error, and have updated the example repo to demonstrate it working. 

I'm not sure what changed, but thanks again for your help!
