### ISSUE TITLE
YAMLLoadWarning

### ISSUE THREAD

**Issue by OisinMoran** [launchdarkly/python-server-sdk#136]
**Is this a support request?**
No

**Describe the bug**
Using Launch Darkly in Python 3.6 gives the following warning:

```
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated ...
```

Further details can be found here:
https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation

Is there a plan to update this?

**To reproduce**
```
import ldclient
ldclient.get().variation(...)
```

**Expected behavior**
No warnings

**Logs**
```
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the 
default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
```

**SDK version**
`launchdarkly-server-sdk==6.11.1`

**Language version, developer tools**
Python 3.6

**OS/platform**
Ubuntu 18.04

**Additional context**
None

**Comment by eli-darkly** [comment]
Is the code shown under "to reproduce" really the entirety of the steps to reproduce? I presume you're setting an SDK key that's not shown here, but are you using any other configuration options? The SDK never calls `yaml.load()` unless 1. you are explicitly calling the test tool `Files.new_data_source` and 2. the `pyyaml` package is installed. It looks like we do need to update our implementation of the file data source tool, but I'm having trouble seeing why you would get such a warning with a default configuration since that code would not be in use. I was not able to reproduce what you're seeing in 3.6 with those minimal test steps.

**Comment by OisinMoran** [comment]
Ah terribly sorry (and thanks for the speedy response), you're right that doesn't reproduce the issue. Here's some more detail from another file where the problem is likely coming from (it's happening while running tests):

```python3
import environ
import ldclient
from ldclient.config import Config
from ldclient.file_data_source import FileDataSource

TEST_RUNNER = "django_nose.NoseTestSuiteRunner"
BASE_DIR = "base_dir"
TMP_DIR = "tmp_dir"
TEST_FILES_DIR = "test_files_dir"
env = environ.Env() 
environ.Env.read_env()
ENV = env('environment')

# Launch Darkly
if ENV == "test":
    factory = FileDataSource.factory(
        paths=[f"{TEST_FILES_DIR}/flagdata.json"],
        auto_update=True
    )
    config = Config(update_processor_class=factory, send_events=False)
    ldclient.set_config(config)

ldclient.set_sdk_key(env('LD_CLIENT_KEY'))
```

**Comment by eli-darkly** [comment]
Got it, that makes sense. Yes, it should be using `safe_load` and we'll patch that ASAP. Meanwhile as long as your input data files don't actually contain deliberate exploits using the `!` operator, your tests should be fine.

**Comment by OisinMoran** [comment]
Super, thanks!

**Comment by eli-darkly** [comment]
@OisinMoran Could you tell me what version of `pyyaml` you have installed?

**Comment by OisinMoran** [comment]
`PyYAML==5.2`

Also two quick questions:
1) Would you be able to give a rough estimate of when this could be fixed?
2) In the meantime what would you suggest the best fix is? At the moment I have added `PyYAML` to the requirements file and in every file that imports ldclient I have added:
```
import yaml
yaml.warnings({'YAMLLoadWarning': False})
```
which seems to do the trick, but is not particularly elegant.

Thanks again for the quick responses!

**Comment by eli-darkly** [comment]
@OisinMoran We should be able to get the patch out tomorrow - there have just been a lot of things going on, plus I was having trouble actually reproducing this issue, which I normally like to do before the fix just on principle. But if I still can't reproduce it right now I'll just do the fix anyway.

In the meantime - if you're not actually _using_ YAML, then _uninstalling_ `pyyaml` would fix this. It detects when the package is present and, if so, uses it to load both YAML and JSON files since technically JSON is a subset of YAML. If the package isn't present, it falls back to just using the JSON parser.

**Comment by eli-darkly** [comment]
Also, if that's not practical, your current workaround makes sense but I believe you would only need to do it in whatever file originally causes the LD client to be created, not every time you import the package.

**Comment by eli-darkly** [comment]
We didn't get the patch out on Friday, but it's out now: version 6.11.2 should fix this.
