### ISSUE TITLE
Python SDK is not updating the 'Evaluated ...' value for the flag

### ISSUE THREAD

**Issue by hoppy1977** [launchdarkly/python-server-sdk#151]
**Describe the bug**
When I use the Python SDK to check the value of a Feature flag, it is not updating the 'Evaluated ...' value. I.e. the value for the flag still reads as 'Evaluated 9 days ago', even though I just accessed (and got a valid response back from) the flag.
However, if I call `ldclient.get().close()`, it works.
The [documentation](https://docs.launchdarkly.com/sdk/server-side/python#close) states that "In most long-running applications, you should not have to call close", which makes sense to me. Shouldn't calling `flush` be enough?

**To reproduce**
Simply call `ld_client.variation`, _without_ calling `close` afterwards.
See [here](https://github.com/hoppy1977/ld-test.git) for an example.

**Expected behavior**
Every time I call `flush` it should update the value displayed in the Launch Darkly user interface.

**Logs**
N/A

**SDK version**
7.0.1

**Language version, developer tools**
Python 3.9.1

**OS/platform**
Windows 10

**Additional context**
N/A

**Comment by InTheCloudDan** [comment]
@hoppy1977 `flush` schedules the events to get sent to LaunchDarkly, it does not immediately send. Here's the SDK docs covering it: https://github.com/launchdarkly/python-server-sdk/blob/4a26691cbe659ace1627b9f861f34acb24e0515d/ldclient/client.py#L222-L225

Based on the example code you are still exiting almost immediately after evaluating, if you run it for longer the evaluations should send. If you are still running into problems with it please open a ticket with support@launchdarkly.com we'll be happy to help.

**Comment by eli-darkly** [comment]
@hoppy1977 This is working as intended— and working as documented, although the specific documentation you pointed to could and should be improved.

The key phrase in the text you quoted is "_long-running_ applications". What you wrote in your example code is the opposite of a long-running application: you're evaluating a flag, and then immediately quitting. This means that the SDK does not have time to deliver analytics events, which, as @InTheCloudDan pointed out, is done asynchronously; Flush means "flush as soon as you get a chance" rather than "don't return from this call until you're done". By design, the SDK does almost everything asynchronously except for the actual determination of the flag value; this is because it's often used in very high-traffic applications where it's undesirable to make the application wait for anything.

Also, in general I recommend reading not only the "Python SDK reference" page you linked to, which is an overview of the SDK's features, but also the [complete API functionality](https://launchdarkly-python-sdk.readthedocs.io/en/latest/) which describes every method and its parameters in detail (it is generated from the same in-code documentation that @InTheCloudDan cited). I do think we need to update the "reference" page because its description of Flush right now is misleading— given its description of using Flush as part of a one-off test, I can see how you could make the assumption you did (I think that that text is actually left over from a fairly old version of the SDK in which Flush was synchronous). But that is a problem with the documentation, not with the behavior of the SDK.
