### ISSUE TITLE
Thread exception

### ISSUE THREAD

**Issue by ziafnadeem** [launchdarkly/python-server-sdk#156]
I am using python 2.7.15, ldclient-py=6.0.0, i dont want to call the ldclient.close() method as this is a long running application, i am getting the following error.
File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
Traceback (most recent call last): File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner File "/env/local/lib/python2.7/site-packages/ldclient/repeating_timer.py", line 12, in runTraceback (most recent call last): File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
__bootstrap_inner

**Comment by bwoskow-ld** [comment]
Hi @ziafnadeem ,

Version 6.0.0 was released almost two years ago and is no longer supported. Can you update to the latest 6.x SDK version and try again? As of this writing the latest 6.x version is [6.13.3](https://github.com/launchdarkly/python-server-sdk/releases/tag/6.13.3). Note that we dropped compatibility with Python 2.7 on SDK version 7.x-- as such you'll want to stay on the 6.x major version.

Also note that [we renamed](https://github.com/launchdarkly/python-server-sdk/blob/master/CHANGELOG.md#note-on-future-releases) our SDK package between 6.0.0 and the latest 6.x version.

If you still run into this issue on a supported version of the SDK, it might make more sense to contact our support team at support@launchdarkly.com, rather than using this public GitHub issue tracker, so that you can privately provide code samples and further diagnose your issue.
